### ISSUE TITLE
why thread id is string? And comment ancestors is varchar?

### ISSUE THREAD

**Issue by DaumantasUrb** [FriendsOfSymfony/FOSCommentBundle#519]
just would like to know. Thanks

**Comment by Eatmeatleet** [comment]
There is no point to have thread id as string, as it is also copied inside comment table as foreign key so it takes more space and bad for scaling. There can be another index if needed. 

On ancestors, it should be a one to many relation

**Comment by skylord123** [comment]
I'm a bit confused why the ancestors field is string.

**Comment by shibby** [comment]
As threadId, i think there is no problem with being string. At last, it's primary key and has index. And we can define whatever we want for thread id. for example, i'm using question_{id}, article_{id}, video_{id}. of course i can add extra fields like "type, reference_id" (and i also did) but with this way it's easy to manage. especially for user who are not experienced.

BUT, ancestors field is a really really bad choice because there is `order by` based on ancestors when getting comments. ordering without index AND via string column is really bad solution. this column should change urgently...

**Comment by skylord123** [comment]
Yes I am in support of this being changed. Will someone in charge of the repository respond?

**Comment by shibby** [comment]
It's a really big change. So i'm not it can be changed easily because of backward compability. Actually, i don't know how people use this bundle with this problem. This makes requests so slow. 
Who maintains this bundle? @FriendsOfSymfony It seems it's not actively developing :/

**Comment by shibby** [comment]
@XWB hey, sorry for taking your time. did you see this topic?

**Comment by XWB** [comment]
To be honest I have no idea why `thread_id` is a string, I was not around when this bundle was created. And the original creator is not active anymore.

We could easily changed it though, because the master branch is tagged as 3.0.x-dev and is allowed to be backwards incompatibele with the 2.x branch.

That said, I personally never experienced performance issues with the `ancestors` field. We have threads containing hundreds of comments, and they are loading almost instantly.

> ordering without index AND via string column is really bad solution

This bundle won't stop you from creating your own indexes :)

**Comment by stof** [comment]
@shibby ancestors is a slash-delimited list of ancestors. I don't see another solution than VARCHAR to store this. And replacing the usage of ancestors with a different way to sort comments in the right order when retrieving them is not an easy task (we are talking about returning comments in an order corresponding to a tree traversal).
The only issue I see regarding adding an index is the MySQL support. MySQL has a hard limit on the length of indexed varchar fields, and we have no way to ensure that such limit is not reached in the bundle except by forbidding to reply to comments once the length of the ancestors field reaches the limit. We already suffer from this limitation (without validation in place to prevent issues with the DB failing to store the value of the field or truncating it in the case of non-strict MySQL) but indexing support in MySQL would force to make the limit much lower (180 chars instead of 1024).

Regarding thread_id, switching it from a string to an integer would be a pretty bad BC break, as it could forbid people to upgrade altogether, if they were not using an integer as thread_id (and there is *nothing* enforcing the usage of integers there). Allowing strings for the thread id allows people to build the thread id with a naming convention regarding where these threads are meant to appear (being able to inject the thread easily on the page needing to display it alongside other content).

**Comment by XWB** [comment]
Closing this for now.
