### ISSUE TITLE
override thread controller

### ISSUE THREAD

**Issue by gastonrodriguezgr** [FriendsOfSymfony/FOSCommentBundle#569]
hello i would override thread controller in order to send emails on each comment, how can i do that? thanks!

**Comment by jonathan-huteau** [comment]
Hello @gastonrodriguezgr,

Maybe you could have a look at this doc https://github.com/FriendsOfSymfony/FOSCommentBundle/blob/master/Resources/doc/15-events.md

**Comment by zettsu** [comment]
Hi sorry for comment here don't know where to post my issue I have questions for how to override some methods of /api, in order to add logic and other validations for custom fields. Controller, in particular, is ThreadController I tried to do according to doc but it's not working
You can give me a starting point for this, I read the documentation for Symfony2 http://symfony.com/doc/2.3/cookbook/bundles/inheritance.html, but this doesn't work for this bundle. Thanks and sorry for bad English

**Comment by XWB** [comment]
Have a look at http://symfony.com/doc/current/bundles/inheritance.html as well.
