### ISSUE TITLE
Can't override templates using templates/bundles directory

### ISSUE THREAD

**Issue by mkruk-u2** [FriendsOfSymfony/FOSCommentBundle#635]
We're updating our project to use Symfony 4 and we're trying to move our templates to `templates/` directory.
Since we override some of FOSCommentBundle templates we would like to move them under `templates/bundles/FOSCommentBundle/` (as [suggested here](https://symfony.com/blog/new-in-symfony-3-4-improved-the-overriding-of-templates#new-overriding-directory)) but this doesn't seem to work - our customized templates are not loaded and default bundle templates are still used.

How can we override templates using `templates/` directory?

Our current setup:
- Symfony: 3.4.3
- FOSCommentBundle: dev-master (tested with [0b3b8f7](https://github.com/FriendsOfSymfony/FOSCommentBundle/commit/0b3b8f7ab8eb61d6bc34ecb1e0ff5109ab2d954a))

**Comment by emulienfou** [comment]
Hi @mkruk-u2, I'm in the same situation as you with Symfony 4!

The problem is they use the class `TemplateReference` to call the template file. With this code it seems we cannot override the templates files.

So to fix this issue, we need to replace the code like:
```php
->setTemplate(new TemplateReference('FOSCommentBundle', 'Thread', 'comments'));
```
by
```php
->setTemplate('@FOSComment/Thread/comments.html.twig');
```

I will change the code, test it and do a PullRequest as soon as possible.

**Comment by XWB** [comment]
Should be fixed in https://github.com/FriendsOfSymfony/FOSCommentBundle/pull/651
